# Generated by Django 4.2.15 on 2024-08-27 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsportal', '0002_remove_author_authoruser_delete_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='message',
            new_name='post',
        ),
    ]
